/*
 ============================================================================
 Name        : Parcial.c
 Author      : 
 Version     :
 Copyright   : Your copyright notice
 Description : Hello World in C, Ansi-style
 ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include "Cliente.h"
#include "Estado.h"
#include "RJimenez.h"

#define BIENVENIDA "BIENVENIDO AL ABM DE EMPLEADOS\n"
#define MENSAJE_OPCION_UNO "1.ALTAS\n"
#define MENSAJE_OPCION_DOS "2.MODIFICAR\n"
#define MENSAJE_OPCION_TRES "3.BAJA\n"
#define MENSAJE_OPCION_CUATRO "4.CREAR PEDIDO DE RECOLECCION\n"
#define MENSAJE_OPCION_CINCO "5.PROCESAR RESIDUOS\n"
#define MENSAJE_OPCION_SEIS "6.IMPRIMIR CLIENTES\n"
#define MENSAJE_OPCION_SIETE "7.IMPRIMIR PEDIDOS PENDIENTES\n"
#define MENSAJE_OPCION_OCHO "8.IMPRIMIR PEDIDOS PROCESADOS\n"
#define MENSAJE_OPCION_NUEVE "9.PEDIDOS PENDIENTES POR LOCALIDAD\n"
#define MENSAJE_OPCION_DIEZ "10.CANTIDAD DE KILOS DE POLIPROPILENO RECICLADO PROMEDIO POR CLIENTE\n"
#define MENSAJE_OPCION_ONCE "11.SALIR\n"
#define MENSAJE_INGRESAR_OPCION "INGRESE UNA OPCION: "
#define MENSAJE_ERROR "INGRESO UNA OPCION INCORRECTA, VUELVA A INGRESAR UNA OPCION\n"
#define MENSAJE_DE_DESPEDIDA "USTED HA SALIDO DEL SISTEMA\n"
#define MENSAJE_PEDIR_NOMBRE "INGRESE EL NOMBRE DE LA EMPRESA\n"
#define MENSAJE_ERROR_NOMBRE "ERROR EN EL INGRESO DEL NOMBRE\n\n"
#define MENSAJE_PEDIR_CUIT "INGRESE EL CUIT DE LA EMPRESA\n"
#define MENSAJE_ERROR_CUIT "ERROR EN EL INGRESO DEL CUIT\n\n"
#define MENSAJE_PEDIR_DIRECCION "INGRESE LA DIRECCION DE LA EMPRESA\n"
#define MENSAJE_ERROR_DIRECCION "ERROR EN EL INGRESO DE LA DIRECCION\n\n"
#define MENSAJE_PEDIR_LOCALIDAD "INGRESE LA LOCALIDAD DE LA EMPRESA\n"
#define MENSAJE_ERROR_LOCALIDAD "ERROR EN EL INGRESO DE LA LOCALIDAD\n\n"
#define	MENSAJE_ERROR_LUGAR "NO HAY LUGAR PARA INGRESAR UN NUEVO CLIENTE\n\n"
#define MENSAJE_EXITO_ALTA "EL CLIENTE FUE DADO DE ALTA CON EXITO"
#define MENSAJE_ELIMINAR "POR FAVOR INGRESE EL ID DE LA EMPRESA QUE QUIERE ELIMINAR"
#define MENSAJE_ELIMINACION_EXITOSA "EL CLIENTE FUE DADO DE BAJA CORRECTAMENTE\n\n"
#define MENSAJE_ERROR_NO_ENCONTRADO "EL ID INGRESADO NO FUE ENCONTRADO\n\n"
#define MENSAJE_ERROR_ELIMINAR "NO INGRESO UN ID VALIDO, NO SE HA PODIDO ELIMINAR AL CLIENTE"
#define MENSAJE_MODIFICAR "INGRESE EL ID DEL EMPLEADO QUE QUIERA MODIFICAR: "
#define MENSAJE_ERROR_MODIFICAR "ERROR AL INGRESAR EL ID\n"
#define MENSAJE_OPCIONES_MODIFICACION "ELIJA EL DATO A MODIFICAR:\n\t1. DIRECCION\n\t2. LOCALIDAD\n\nSU OPCION: "
#define	MENSAJE_MODIFICAR_DIRECCION "INGRESE LA DIRECCION DE LA EMPRESA: "
#define MENSAJE_MODIFICAR_LOCALIDAD "INGRESE LA LOCALIDAD DE LA EMPRESA: "
#define MENSAJE_MODIFICAR_DIRECCION_EXITOSA "LA DIRECCION FUE MODIFICADA EXITOSAMENTE\n\n"
#define MENSAJE_MODIFICAR_DIRECCION_ERROR "ERROR AL INGRESAR LA DIRECCION\n\n"
#define MENSAJE_MODIFICAR_LOCALIDAD_EXITOSA "LA LOCALIDAD FUE MODIFICADA EXITOSAMENTE\n\n"
#define MENSAJE_MODIFICAR_LOCALIDAD_ERROR "ERROR AL INGRESAR LA DIRECCION\n\n"
#define MENSAJE_ERROR_OPCION_MODIFICAR "INGRESO UNA OPCION DE MODIFICACION INVALIDA\n\n"
#define MENSAJE_PEDIDO "INGRESE EL ID AL QUE SE LE CARGARA EL PEDIDO"
#define MENSAJE_ERROR_PEDIDO "ERROR AL INGRESAR EL ID"
#define	MENSAJE_CLIENTE_NO_ENCONTRADO "NO SE HA ENCONTRADO EL CLIENTE CON ESE ID"
#define MENSAJE_INGRESAR_KILOS_TOTALES "INGRESE LA CANTIDAD DE KILOS A RECOLECTAR"
#define MENSAJE_ERROR_SIN_PEDIDOS "NO HAY ESPACIO PARA CARGAR PEDIDOS"

#define LARGO_DE_CLIENTES 100
#define LARGO_DE_PEDIDOS 100

int main(void) {

	printf(BIENVENIDA);

	Pedido arrayPedidos [LARGO_DE_PEDIDOS];
	Estado arrayEstados [2];
	Cliente arrayClientes [LARGO_DE_CLIENTES];
	int idCliente;
	int idPedido;
	int opcion;


	iniciarEstado (arrayEstados);
	IniciarCliente (arrayClientes, LARGO_DE_CLIENTES);
	idCliente = 1;

	setbuf(stdout, NULL);



	do
	{
		printf("\n\n");

		printf(MENSAJE_OPCION_UNO);
		printf(MENSAJE_OPCION_DOS);
		printf(MENSAJE_OPCION_TRES);
		printf(MENSAJE_OPCION_CUATRO);
		printf(MENSAJE_OPCION_CINCO);
		printf(MENSAJE_OPCION_SEIS);
		printf(MENSAJE_OPCION_SIETE);
		printf(MENSAJE_OPCION_OCHO);
		printf(MENSAJE_OPCION_NUEVE);
		printf(MENSAJE_OPCION_DIEZ);
		printf(MENSAJE_OPCION_ONCE);

		PedirInt(MENSAJE_INGRESAR_OPCION, &opcion);


		switch(opcion)
		{
			case 1:
				PedirCliente(MENSAJE_PEDIR_NOMBRE, MENSAJE_ERROR_NOMBRE, MENSAJE_PEDIR_CUIT, MENSAJE_ERROR_CUIT, MENSAJE_PEDIR_DIRECCION,
						MENSAJE_ERROR_DIRECCION, MENSAJE_PEDIR_LOCALIDAD, MENSAJE_ERROR_LOCALIDAD, idCliente, LARGO_DE_CLIENTES, arrayClientes,
						MENSAJE_ERROR_LUGAR, MENSAJE_EXITO_ALTA);
					idCliente ++;
				break;
			case 2:
				ModificarCliente (MENSAJE_MODIFICAR, MENSAJE_ERROR_NO_ENCONTRADO, MENSAJE_ERROR_MODIFICAR, MENSAJE_OPCIONES_MODIFICACION,
						MENSAJE_MODIFICAR_DIRECCION, MENSAJE_MODIFICAR_LOCALIDAD, MENSAJE_MODIFICAR_DIRECCION_EXITOSA, MENSAJE_MODIFICAR_DIRECCION_ERROR,
						MENSAJE_MODIFICAR_LOCALIDAD_EXITOSA, MENSAJE_MODIFICAR_LOCALIDAD_ERROR, MENSAJE_ERROR_OPCION_MODIFICAR, arrayClientes, LARGO_DE_CLIENTES);
				break;
			case 3:
				PedirEliminacionDelCliente(arrayClientes, LARGO_DE_CLIENTES, MENSAJE_ELIMINAR, MENSAJE_ELIMINACION_EXITOSA, MENSAJE_ERROR_NO_ENCONTRADO,
						MENSAJE_ERROR_ELIMINAR);
				break;
			case 4:
				PedidoDeRecoleccion(MENSAJE_PEDIDO, MENSAJE_ERROR_PEDIDO, arrayClientes, LARGO_DE_CLIENTES, arrayPedidos, LARGO_DE_PEDIDOS, arrayEstados,
						MENSAJE_CLIENTE_NO_ENCONTRADO, MENSAJE_INGRESAR_KILOS_TOTALES, MENSAJE_ERROR_SIN_PEDIDOS, idPedido);
				break;
			case 5:

				break;
			case 6:

				break;
			case 7:

				break;
			case 8:

				break;
			case 9:

				break;
			case 10:

				break;
			case 11:

				break;
			default:
				printf("Hola default");
				break;
		}

	} while(opcion != '5');

	return EXIT_SUCCESS;
}
